org: josfy
app: fx-rate-history
service: fx-rate-history-backend

provider:
  name: aws
  region: us-west-2
  stage: dev
  runtime: python3.8
  timeout: 30
  environment:
    PYTHONPATH: "/opt/python:/opt/python/lib/${self:provider.runtime}/site-packages:src"

custom:
  dotenv:
    path: .env
  pythonRequirements:
    layer: true
    slim: false
    useStaticCache: false
  wsgi:
    app: src.app.app

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline

package:
  individually: false
  patterns:
    - '!**'
    - '!**/tests/**'
    - "**/serverless_sdk/**"
    - "**/s_*.py"
    - 'src/**'

functions:
  dataCollector:
    handler: src.lambda_handler.data_collector_handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - schedule: rate(1 minute)

