org: josfy
app: fx-rate-history
service: fx-rate-history-backend

provider:
  name: aws
  region: us-west-2
  vpc:
    securityGroupIds:
      - ${param:SECURITY_GROUP_ID}
    subnetIds:
      - ${param:SUBNET_A_ID}
      - ${param:SUBNET_B_ID}
  stage: dev
  runtime: python3.8
  timeout: 30
  environment:
    PYTHONPATH: "/opt/python:/opt/python/lib/${self:provider.runtime}/site-packages:src"
    ENVIRONMENT: ${param:ENVIRONMENT}
    DATASOURCE_HOST: ${param:DATASOURCE_HOST}
    DATASOURCE_API_KEY: ${param:DATASOURCE_API_KEY}
    DB_CONN: postgresql://${param:DB_USERNAME}:${param:DB_PASSWORD}@${param:DB_HOST}/${param:DB_NAME}
    FLASK_APP: ${param:FLASK_APP}

custom:
  dotenv:
    path: .env
  pythonRequirements:
    layer: true
    slim: false
    useStaticCache: false
  wsgi:
    app: ${param:FLASK_APP}.app
  scripts:
    commands:
      flask-shell: flask shell
      flask-db-init: python -m pipenv run flask db init
      flask-db-rev: python -m pipenv run flask db migrate
      flask-db-up: python -m pipenv run flask db upgrade head
      run-unit-tests: python -m pipenv run pytest

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline
  - serverless-plugin-scripts

package:
  individually: false
  patterns:
    - '!**'
    - '!**/tests/**'
    - "**/serverless_sdk/**"
    - "**/s_*.py"
    - 'src/**'

functions:
  dataCollector:
    handler: src.lambda_handler.data_collector_handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - schedule: rate(1 hour)

