DEFAULT_MENU = [
    {"name": "Pork chop"},
    {"name": "Rice"},
    {"name": "Chopsuey"},
    {"name": "Adobo"},
    {"name": "Bulalo"},
    {"name": "Siopao"},
    {"name": "Burger"},
    {"name": "Chicken mami"},
    {"name": "Longsilog"},
    {"name": "Tosilog"},
    {"name": "Tapsilog"},
    {"name": "Pancit"},
    {"name": "Lugaw"},
    {"name": "Lomi"},
    {"name": "Tokwa't baboy"},
    {"name": "Beef pares"},
    {"name": "Fried siomai"},
    {"name": "Water", "quantity": -1}
]